language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_2724e30f1ad9_key -iv $encrypted_2724e30f1ad9_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
