language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_505f70dda23f_key -iv $encrypted_505f70dda23f_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
